import {
  ActionType,
  AgentProviderType,
  AiProviderType,
  ChatCompletionContentPart,
  ComponentDecisionV2,
  DeprecatedComposioAuthMode,
  GenerationStage,
  LogLevel,
  MCPTransport,
  MessageRole,
  OAuthClientInformation,
  OAuthTokens,
  OAuthValidationMode,
  SessionClientInformation,
  SessionSource,
  ToolCallRequest,
  ToolProviderType,
  V1RunError,
  V1RunStatus,
  type CustomLlmParameters,
} from "@tambo-ai-cloud/core";
import { relations, sql } from "drizzle-orm";
import {
  boolean,
  check,
  foreignKey,
  index,
  integer,
  pgPolicy,
  pgRole,
  pgSchema,
  pgTable,
  primaryKey,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import { authenticatedRole, authUid } from "drizzle-orm/supabase";
import { customJsonb } from "./drizzleUtil";
export { authenticatedRole, authUid } from "drizzle-orm/supabase";

/** Use this to get the project id from the api key */
export const projectApiKeyVariable = sql`current_setting('request.apikey.project_id')`;
export const projectApiKeyRole = pgRole("project_api_key", {
  inherit: true,
});

/** Anon role for unauthenticated requests (e.g., device auth initiation/polling)
 * Note: Role is created via custom migration 0083_add-anon-role.sql.
 * See that migration for details on why we use pgRole() with no options here.
 */
export const anonRole = pgRole("anon").existing();

// User schema for NextAuth adapter tables
export const authSchema = pgSchema("auth");

export const authUsers = authSchema.table(
  "users",
  ({ text, timestamp, uuid, jsonb }) => ({
    id: uuid("id").primaryKey().notNull(),
    email: text("email"),
    emailConfirmedAt: timestamp("email_confirmed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    rawUserMetaData: jsonb("raw_user_meta_data").default({}),
  }),
  (table) => [index("user_email_idx").on(table.email)],
);

export const identities = authSchema.table(
  "identities",
  ({ text, timestamp, uuid, jsonb }) => ({
    id: uuid("id").primaryKey().notNull(),
    userId: uuid("user_id")
      .references(() => authUsers.id, { onDelete: "cascade" })
      .notNull(),
    provider: text("provider").notNull(),
    providerId: text("provider_id").notNull(),
    identityData: jsonb("identity_data").default({}),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  }),
  (table) => [
    index("identity_provider_provider_id_idx").on(
      table.provider,
      table.providerId,
    ),
    index("identity_user_id_idx").on(table.userId),
  ],
);

/**
 * @deprecated UNUSED with JWT strategy - NextAuth stores sessions in JWT cookies, not DB.
 * Kept for historical reference only. Use `sessions` table in public schema instead.
 */
export const authSessions = authSchema.table(
  "sessions",
  ({ text, timestamp, uuid }) => ({
    id: text("id").primaryKey().notNull(),
    userId: uuid("user_id")
      .references(() => authUsers.id, { onDelete: "cascade" })
      .notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    notAfter: timestamp("not_after", { withTimezone: true }),
  }),
  (table) => [
    index("session_user_id_idx").on(table.userId),
    index("session_not_after_idx").on(table.notAfter),
  ],
);

/**
 * Unified sessions table for tracking ALL authentication sessions
 *
 * - Browser sessions: Audit entries created on NextAuth signIn (JWT controls actual auth)
 * - CLI sessions: Device auth flow, revocable, token IS the credential
 *
 * NOTE: auth.sessions is unused with JWT strategy - this is the source of truth for session tracking.
 *
 * NOTE: Token stored as `id` for CLI sessions is a 256-bit high-entropy credential - NEVER log it.
 *
 * Design note: Using the token as PK (rather than bigserial + separate token column) enables
 * single PK lookup during auth validation, which is the most performance-critical path.
 */
export const sessions = pgTable(
  "sessions",
  ({ text, timestamp, uuid }) => ({
    // For CLI: High-entropy session token (256 bits, base64url encoded) - this IS the credential
    // For browser: Random UUID generated by Postgres - just an audit trail ID
    // WARNING: This ID must NEVER be logged or exposed publicly for CLI sessions
    id: text("id")
      .primaryKey()
      .notNull()
      .default(sql`gen_random_uuid()::text`),
    // The user who owns this session
    userId: uuid("user_id")
      .references(() => authUsers.id, { onDelete: "cascade" })
      .notNull(),
    // Session origin: 'browser' or 'cli'
    source: text("source", {
      enum: Object.values(SessionSource) as [SessionSource],
    }).notNull(),
    // When this session expires (default: 90 days from creation)
    expiresAt: timestamp("expires_at", { withTimezone: true })
      .default(sql`now() + interval '90 days'`)
      .notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  }),
  (table) => [
    index("sessions_user_id_idx").on(table.userId),
    index("sessions_expires_at_idx").on(table.expiresAt),
    index("sessions_source_idx").on(table.source),
  ],
);

export type DBSession = typeof sessions.$inferSelect;

/**
 * Device auth codes for CLI authentication (OAuth 2.0 Device Authorization Grant)
 * These are temporary codes that expire after 15 minutes.
 * Once a code is verified, a session is created in the sessions table.
 */
export const deviceAuthCodes = pgTable(
  "device_auth_codes",
  ({ text, timestamp, uuid, boolean }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('dac_')`),
    // Server-generated UUID used by CLI to poll for completion (generated by Postgres)
    deviceCode: uuid("device_code")
      .notNull()
      .unique()
      .default(sql`gen_random_uuid()`),
    // Human-friendly 8-character code shown to user (e.g., "WDJB-MJHT" stored as "WDJBMJHT")
    userCode: text("user_code").notNull().unique(),
    // Set when user verifies the code in browser
    userId: uuid("user_id").references(() => authUsers.id, {
      onDelete: "cascade",
    }),
    // The session ID created when verification completes
    sessionId: text("session_id").references(() => sessions.id, {
      onDelete: "cascade",
    }),
    // Prevent reuse of codes
    isUsed: boolean("is_used").default(false).notNull(),
    // Codes expire after 15 minutes
    expiresAt: timestamp("expires_at", { withTimezone: true })
      .default(sql`now() + interval '15 minutes'`)
      .notNull(),
    // Track last poll time for server-side rate limiting
    lastPolledAt: timestamp("last_polled_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  }),
  (table) => [
    index("device_auth_codes_device_code_idx").on(table.deviceCode),
    index("device_auth_codes_user_code_idx").on(table.userCode),
    index("device_auth_codes_expires_at_idx").on(table.expiresAt),
    // Anon role policies for device auth flow (CLI initiation + polling)
    pgPolicy("device_auth_anon_insert", {
      to: anonRole,
      for: "insert",
      withCheck: sql`true`,
    }),
    pgPolicy("device_auth_anon_select", {
      to: anonRole,
      for: "select",
      using: sql`true`,
    }),
    pgPolicy("device_auth_anon_update", {
      to: anonRole,
      for: "update",
      using: sql`true`,
    }),
    // Authenticated role can also manage device auth codes (for verify flow)
    pgPolicy("device_auth_authenticated_all", {
      to: authenticatedRole,
      using: sql`true`,
    }),
  ],
).enableRLS();

export type DBDeviceAuthCode = typeof deviceAuthCodes.$inferSelect;

export const sessionRelations = relations(sessions, ({ one }) => ({
  user: one(authUsers, {
    fields: [sessions.userId],
    references: [authUsers.id],
  }),
}));

export const deviceAuthCodeRelations = relations(
  deviceAuthCodes,
  ({ one }) => ({
    user: one(authUsers, {
      fields: [deviceAuthCodes.userId],
      references: [authUsers.id],
    }),
    session: one(sessions, {
      fields: [deviceAuthCodes.sessionId],
      references: [sessions.id],
    }),
  }),
);

// Relations for user schema tables
export const userSchemaUserRelations = relations(authUsers, ({ many }) => ({
  identities: many(identities),
  sessions: many(sessions),
  projects: many(projectMembers),
}));

export const userSchemaIdentityRelations = relations(identities, ({ one }) => ({
  user: one(authUsers, {
    fields: [identities.userId],
    references: [authUsers.id],
  }),
}));

// Export types for user schema tables
export type DBUser = typeof authUsers.$inferSelect;
export type DBIdentity = typeof identities.$inferSelect;
/** @deprecated Use DBSession from public sessions table instead */
export type DBAuthSession = typeof authSessions.$inferSelect;

export const projects = pgTable(
  "projects",
  ({ text, timestamp, uuid, boolean }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('p_')`),
    /** @deprecated - Last time a project was used with a legacy id was 2025-04-28 20:33:58.371+00 */
    deprecated_legacyId: text("legacy_id").unique(),
    name: text("name").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    creatorId: uuid("creator_id")
      .references(() => authUsers.id)
      // Need to write raw `auth.uid()` because ${authUid} includes a select statement
      .default(sql`auth.uid()`),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow(),
    /** @deprecated - everyone has mcp now */
    deprecated_mcpEnabled: boolean("mcp_enabled").default(false).notNull(),
    /** @deprecated - everyone has mcp now */
    deprecatedComposioEnabled: boolean("composio_enabled")
      .default(false)
      .notNull(),
    /** Additional instructions that are injected into the system prompt */
    customInstructions: text("custom_instructions"),
    // New fields for default LLM configuration choices
    defaultLlmProviderName: text("default_llm_provider_name"), // e.g., "openai", "anthropic"
    defaultLlmModelName: text("default_llm_model_name"), // e.g., "gpt-4o", "claude-3-opus-20240229"
    customLlmModelName: text("custom_llm_model_name"), // custom model name for "openai-compatible" provider type
    customLlmBaseURL: text("custom_llm_base_url"), // For "openai-compatible" provider type
    maxInputTokens: integer("max_input_tokens"), // Maximum number of input tokens to send to the model
    maxToolCallLimit: integer("max_tool_call_limit").default(10).notNull(), // Maximum number of tool calls allowed per response
    // Whether end-users are allowed to provide system prompts when creating/advancing threads
    allowSystemPromptOverride: boolean("allow_system_prompt_override")
      .default(false)
      .notNull(),
    // OAuth token validation settings
    oauthValidationMode: text("oauth_validation_mode", {
      enum: Object.values(OAuthValidationMode) as [OAuthValidationMode],
    })
      .notNull()
      .default(OAuthValidationMode.ASYMMETRIC_AUTO), // Default to no validation
    oauthSecretKeyEncrypted: text("oauth_secret_key_encrypted"), // Encrypted secret key for symmetric validation
    oauthPublicKey: text("oauth_public_key"), // Public key for manual asymmetric validation
    // Secret used to sign/verify first-party OAuth bearer access tokens issued by our API.
    // Generated per-project by Postgres with strong entropy. Kept server-side only.
    bearerTokenSecret: text("bearer_token_secret")
      .notNull()
      .default(sql`encode(gen_random_bytes(32), 'hex')`),
    isTokenRequired: boolean("is_token_required").default(false).notNull(),
    providerType: text("provider_type", {
      enum: Object.values<string>(AiProviderType) as [AiProviderType],
    })
      .default(AiProviderType.LLM)
      .notNull(),
    agentProviderType: text("agent_provider_type", {
      enum: Object.values<string>(AgentProviderType) as [AgentProviderType],
    })
      .default(AgentProviderType.AGUI)
      .notNull(),
    agentUrl: text("agent_url"),
    agentName: text("agent_name"),
    customLlmParameters: customJsonb<CustomLlmParameters>(
      "custom_llm_parameters",
    ),
    agentHeaders: customJsonb<Record<string, string>>("agent_headers"),
  }),
  (table) => {
    return [
      index("projects_creator_id_idx").on(table.creatorId),
      pgPolicy("project_user_select_policy", {
        to: authenticatedRole,
        for: "select",
        using: sql`
          exists (
            select 1 
            from project_members 
            where project_members.project_id = ${table.id} 
              and project_members.user_id = ${authUid}
          ) or (
            ${table.creatorId} is not null 
            and ${table.creatorId} = ${authUid}
          )
        `,
      }),
      pgPolicy("project_user_update_policy", {
        to: authenticatedRole,
        for: "update",
        using: sql`exists (select 1 from project_members where project_members.project_id = ${table.id} and project_members.user_id = ${authUid})`,
      }),
      pgPolicy("project_user_delete_policy", {
        to: authenticatedRole,
        for: "delete",
        using: sql`exists (select 1 from project_members where project_members.project_id = ${table.id} and project_members.user_id = ${authUid})`,
      }),
      pgPolicy("project_user_insert_policy", {
        to: authenticatedRole,
        for: "insert",
        withCheck: sql`true`,
      }),
      pgPolicy("project_api_key_policy", {
        to: projectApiKeyRole,
        for: "select",
        using: sql`${table.id} = (select ${projectApiKeyVariable})`,
      }),
    ];
  },
);

export type DBProject = typeof projects.$inferSelect;
export const projectMembers = pgTable(
  "project_members",
  ({ uuid, text, timestamp, bigserial }) => ({
    id: bigserial("id", { mode: "bigint" }).primaryKey(),
    projectId: text("project_id")
      .references(() => projects.id)
      .notNull(),
    userId: uuid("user_id")
      .references(() => authUsers.id)
      .notNull(),
    role: text("role").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  }),
  (table) => {
    return [
      index("project_members_project_id_idx").on(table.projectId),
      index("project_members_user_id_idx").on(table.userId),
      pgPolicy("project_members_user_policy", {
        to: authenticatedRole,
        using: sql`${table.userId} = ${authUid}`,
      }),
      pgPolicy("project_members_api_key_policy", {
        to: projectApiKeyRole,
        using: sql`${table.projectId} = (select ${projectApiKeyVariable})`,
      }),
    ];
  },
);
export type DBProjectMember = typeof projectMembers.$inferSelect;
export const projectMembersRelations = relations(projectMembers, ({ one }) => ({
  project: one(projects, {
    fields: [projectMembers.projectId],
    references: [projects.id],
  }),
  user: one(authUsers, {
    fields: [projectMembers.userId],
    references: [authUsers.id],
  }),
}));

export const apiKeys = pgTable(
  "api_keys",
  ({ text, timestamp, uuid }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('hk_')`),
    name: text("name").notNull(),
    hashedKey: text("hashed_key").notNull(),
    partiallyHiddenKey: text("partially_hidden_key"),
    projectId: text("project_id")
      .references(() => projects.id)
      .notNull(),
    createdByUserId: uuid("created_by_user_id")
      .references(() => authUsers.id)
      .notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
  }),
  (table) => [
    index("api_keys_project_id_idx").on(table.projectId),
    index("api_keys_created_by_user_id_idx").on(table.createdByUserId),
  ],
);
export type DBApiKey = typeof apiKeys.$inferSelect;
export const apiKeyRelations = relations(apiKeys, ({ one }) => ({
  createdBy: one(authUsers, {
    fields: [apiKeys.createdByUserId],
    references: [authUsers.id],
  }),
  project: one(projects, {
    fields: [apiKeys.projectId],
    references: [projects.id],
  }),
}));

export const providerKeys = pgTable(
  "provider_keys",
  ({ text, timestamp }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('pvk_')`),
    projectId: text("project_id")
      .references(() => projects.id)
      .notNull(),
    providerName: text("provider_name").notNull(),
    providerKeyEncrypted: text("provider_key_encrypted").notNull(),
    partiallyHiddenKey: text("partially_hidden_key"),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    lastUsedAt: timestamp("last_used_at", { withTimezone: true }),
  }),
  (table) => [index("provider_keys_project_id_idx").on(table.projectId)],
);

export const providerKeyRelations = relations(providerKeys, ({ one }) => ({
  project: one(projects, {
    fields: [providerKeys.projectId],
    references: [projects.id],
  }),
}));

export const projectMessageUsage = pgTable(
  "project_message_usage",
  ({ text, timestamp, integer, boolean }) => ({
    projectId: text("project_id")
      .references(() => projects.id, { onDelete: "cascade" })
      .primaryKey()
      .notNull(),
    messageCount: integer("message_count").notNull().default(0),
    hasApiKey: boolean("has_api_key").notNull().default(false),
    createdAt: timestamp("created_at").notNull().defaultNow(),
    updatedAt: timestamp("updated_at").notNull().defaultNow(),
    notificationSentAt: timestamp("notification_sent_at"),
    firstMessageSentAt: timestamp("first_message_sent_at"),
  }),
);

export const projectRelations = relations(projects, ({ many, one }) => ({
  members: many(projectMembers),
  apiKeys: many(apiKeys),
  providerKeys: many(providerKeys),
  creator: one(authUsers, {
    fields: [projects.creatorId],
    references: [authUsers.id],
  }),
  messageUsage: one(projectMessageUsage, {
    fields: [projects.id],
    references: [projectMessageUsage.projectId],
  }),
  toolProviders: many(toolProviders),
}));

export const threads = pgTable(
  "threads",
  ({ text, timestamp }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('thr_')`),
    name: text("name"),
    projectId: text("project_id")
      .references(() => projects.id)
      .notNull(),
    // this is effectively the end-user id
    contextKey: text("context_key"),
    metadata: customJsonb<Record<string, unknown>>("metadata"),
    generationStage: text("generation_stage", {
      enum: Object.values<string>(GenerationStage) as [GenerationStage],
    })
      .default(GenerationStage.IDLE)
      .notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),

    // ==========================================
    // V1 API run lifecycle fields
    // ==========================================

    // Current run lifecycle (only relevant while runStatus !== "idle")
    runStatus: text("run_status", {
      enum: Object.values<string>(V1RunStatus) as [V1RunStatus],
    })
      .default(V1RunStatus.IDLE)
      .notNull(),
    currentRunId: text("current_run_id"),
    statusMessage: text("status_message"), // Human-readable detail (e.g., "Fetching weather data...")

    // Last run outcome (cleared when next run starts)
    lastRunCancelled: boolean("last_run_cancelled"),
    lastRunError: customJsonb<V1RunError>("last_run_error"),

    // Next run requirements
    pendingToolCallIds: customJsonb<string[]>("pending_tool_call_ids"),
    lastCompletedRunId: text("last_completed_run_id"),
  }),
  (table) => {
    return [
      // Existing index for quick lookup by context key (end-user ID)
      index("threads_context_key_idx").on(table.contextKey),
      // New index to accelerate look-ups and sorting by the most recently
      // updated thread within a project.
      // The composite index (project_id, updated_at) supports queries where
      // we aggregate or order threads by their updated timestamp for a given
      // project (e.g. MAX(updated_at) GROUP BY project_id).
      index("threads_project_updated_idx").on(table.projectId, table.updatedAt),
      // Stand-alone index on updated_at to aid generic recency queries.
      index("threads_updated_at_idx").on(table.updatedAt),
      // Stand-alone index on project_id for filtering threads by project.
      index("threads_project_id_idx").on(table.projectId),
      // Stand-alone index on created_at for sorting/filtering by creation time.
      index("threads_created_at_idx").on(table.createdAt),
      // Note: threads.current_run_id -> runs.id FK is added via migration SQL
      // to avoid circular type inference issues between threads and runs tables
    ];
  },
);
export type DBThread = typeof threads.$inferSelect;

/**
 * Run request parameters stored for auditing/debugging.
 * Only model is a separate column; other parameters are bundled here.
 */
export interface RunRequestParams {
  maxTokens?: number;
  temperature?: number;
  toolChoice?: string | { name: string };
  [key: string]: unknown;
}

/**
 * Runs table for tracking individual generation runs within a thread.
 * Each run represents a single request/response cycle, including tool calls.
 */
export const runs = pgTable(
  "runs",
  ({ text, timestamp, boolean }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('run_')`),
    threadId: text("thread_id")
      .references(() => threads.id, { onDelete: "cascade" })
      .notNull(),

    // Run status lifecycle
    status: text("status", {
      enum: Object.values<string>(V1RunStatus) as [V1RunStatus],
    })
      .default(V1RunStatus.WAITING)
      .notNull(),
    statusMessage: text("status_message"), // "Fetching weather data..."

    // Error tracking (populated when status indicates failure)
    errorCode: text("error_code"),
    errorMessage: text("error_message"),

    // Tool call state
    pendingToolCallIds: customJsonb<string[]>("pending_tool_call_ids"),

    // Continuation chain (self-reference for run chains)
    previousRunId: text("previous_run_id"),

    // Request parameters (for auditing/replay)
    model: text("model"),
    requestParams: customJsonb<RunRequestParams>("request_params"),

    // Metadata
    metadata: customJsonb<Record<string, unknown>>("metadata"),

    // Whether this run was cancelled
    isCancelled: boolean("is_cancelled").default(false).notNull(),

    // Timestamps
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }), // First content received
    completedAt: timestamp("completed_at", { withTimezone: true }), // Run finished
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  }),
  (table) => [
    index("runs_thread_id_idx").on(table.threadId),
    index("runs_status_idx").on(table.status),
    index("runs_created_at_idx").on(table.createdAt),
  ],
);

export type DBRun = typeof runs.$inferSelect;

export const runRelations = relations(runs, ({ one }) => ({
  thread: one(threads, {
    fields: [runs.threadId],
    references: [threads.id],
  }),
  previousRun: one(runs, {
    fields: [runs.previousRunId],
    references: [runs.id],
    relationName: "runChain",
  }),
}));

export const messages = pgTable(
  "messages",
  ({ text, timestamp, boolean }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('msg_')`),
    threadId: text("thread_id")
      .references(() => threads.id)
      .notNull(),
    parentMessageId: text("parent_message_id"),
    role: text("role", {
      enum: Object.values<string>(MessageRole) as [MessageRole],
    }).notNull(),
    content: customJsonb<ChatCompletionContentPart[]>("content").notNull(),
    reasoning: customJsonb<string[]>("reasoning"),
    reasoningDurationMS: integer("reasoning_duration_ms"),
    additionalContext:
      customJsonb<Record<string, unknown>>("additional_context"),
    toolCallId: text("tool_call_id"),
    componentDecision: customJsonb<ComponentDecisionV2>("component_decision"),
    componentState: customJsonb<Record<string, unknown>>("component_state"),
    toolCallRequest: customJsonb<ToolCallRequest>("tool_call_request"),
    actionType: text("action_type", {
      enum: Object.values<string>(ActionType) as [ActionType],
    }),
    error: text("error"),
    metadata: customJsonb<Record<string, unknown>>("metadata"),
    isCancelled: boolean("is_cancelled").default(false).notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .default(sql`clock_timestamp()`)
      .notNull(),
  }),
  (table) => {
    return [
      index("messages_thread_id_idx").on(table.threadId),
      // Prevent direct cycles: a message cannot be its own parent
      check(
        "chk_messages_parent_not_self",
        sql`${table.parentMessageId} IS NULL OR ${table.parentMessageId} <> ${table.id}`,
      ),
      check(
        "chk_messages_reasoning_max_len",
        sql`${table.reasoning} IS NULL
            OR (jsonb_typeof(${table.reasoning}->'json') = 'array' AND
                jsonb_array_length(${table.reasoning}->'json') <= 200)`,
      ),
      index("messages_parent_message_id_idx").on(table.parentMessageId),
      index("messages_thread_id_parent_message_id_idx").on(
        table.threadId,
        table.parentMessageId,
      ),
      // Ensure a parent belongs to the same thread by:
      // 1) creating a unique constraint on (thread_id, id)
      // 2) adding a composite FK (thread_id, parent_message_id) -> (thread_id, id)
      unique("messages_thread_id_id_uniq").on(table.threadId, table.id),
      foreignKey({
        name: "messages_parent_same_thread_fk",
        columns: [table.threadId, table.parentMessageId],
        foreignColumns: [table.threadId, table.id],
      })
        .onDelete("cascade")
        .onUpdate("cascade"),
    ];
  },
);

export type DBMessage = typeof messages.$inferSelect;
export type DBMessageWithThread = DBMessage & {
  thread: DBThread;
};
export type DBMessageWithSuggestions = DBMessage & {
  suggestions: DBSuggestion[];
};

export const threadRelations = relations(threads, ({ one, many }) => ({
  project: one(projects, {
    fields: [threads.projectId],
    references: [projects.id],
  }),
  messages: many(messages),
  runs: many(runs),
}));
export type DBThreadWithMessages = DBThread & {
  messages: DBMessageWithSuggestions[];
};

export const messageRelations = relations(messages, ({ one, many }) => ({
  thread: one(threads, {
    fields: [messages.threadId],
    references: [threads.id],
  }),
  parentMessage: one(messages, {
    fields: [messages.parentMessageId],
    references: [messages.id],
    relationName: "messageParent",
  }),
  childMessages: many(messages, { relationName: "messageParent" }),
  suggestions: many(suggestions),
}));

export const suggestions = pgTable(
  "suggestions",
  ({ text, timestamp }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('sug_')`),
    messageId: text("message_id")
      .references(() => messages.id)
      .notNull(),
    title: text("title").notNull(),
    detailedSuggestion: text("detailed_suggestion").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  }),
  (table) => {
    return [index("suggestions_message_id_idx").on(table.messageId)];
  },
);

export type DBSuggestion = typeof suggestions.$inferSelect;

export const suggestionRelations = relations(suggestions, ({ one }) => ({
  message: one(messages, {
    fields: [suggestions.messageId],
    references: [messages.id],
  }),
}));

// Contacts table for email collection
export const contacts = pgTable("contacts", ({ text, timestamp, uuid }) => ({
  id: uuid("id").primaryKey().defaultRandom(),
  firstName: text("first_name").notNull(),
  lastName: text("last_name"),
  email: text("email").notNull().unique(),
  metadata: customJsonb<Record<string, unknown>>("metadata"),
  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
}));

export const toolProviders = pgTable(
  "tool_providers",
  ({ text, timestamp, boolean }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('tp_')`),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    projectId: text("project_id")
      .references(() => projects.id)
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    type: text("type", {
      enum: Object.values(ToolProviderType) as [ToolProviderType],
    }).notNull(),
    url: text("url"),
    serverKey: text("server_key").notNull().default(""),
    deprecatedComposioAppId: text("composio_app_id"),
    customHeaders: customJsonb<Record<string, string>>("custom_headers")
      .notNull()
      .default({}),
    mcpTransport: text("mcp_transport", {
      enum: Object.values(MCPTransport) as [MCPTransport],
    })
      .notNull()
      .default(MCPTransport.HTTP),
    mcpRequiresAuth: boolean("mcp_requires_auth").notNull().default(false),
  }),
  (table) => [index("tool_providers_project_id_idx").on(table.projectId)],
);

// The combination of a thread id and a tool provider id gives us a unique session for an MCP tool,
// where we store the MCP session id.
export const mcpThreadSession = pgTable(
  "mcp_thread_session",
  ({ text, timestamp }) => ({
    threadId: text("thread_id")
      .references(() => threads.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      })
      .notNull(),
    toolProviderId: text("tool_provider_id")
      .references(() => toolProviders.id, {
        onDelete: "cascade",
        onUpdate: "cascade",
      })
      .notNull(),
    sessionId: text("session_id").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
  }),
  (table) => [
    primaryKey({
      name: "mcp_thread_session_pk",
      columns: [table.threadId, table.toolProviderId],
    }),
  ],
);

export const toolProviderRelations = relations(
  toolProviders,
  ({ one, many }) => ({
    project: one(projects, {
      fields: [toolProviders.projectId],
      references: [projects.id],
    }),
    contexts: many(toolProviderUserContexts),
  }),
);

/**
 * Pairs a context key with a tool provider. This lets a contextKey have
 * specific auth context for a given toolProvider in a project
 *
 * For now this table doesn't really establish anything other than the existence
 * of a contextKey<->toolProviderId relationship, and when it was established.
 */
export const toolProviderUserContexts = pgTable(
  "tool_provider_user_contexts",
  ({ text, timestamp }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('tpu_')`),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    // this is effectively the end-user id. If null, then this is the default/global context for the tool provider.
    contextKey: text("context_key"),
    toolProviderId: text("tool_provider_id")
      .references(() => toolProviders.id, { onDelete: "cascade" })
      .notNull(),
    deprecatedComposioIntegrationId: text("composio_integration_id"),
    // once the connected account is created, we store the id here - if this is non-null, then we have a connected account
    deprecatedComposioConnectedAccountId: text("composio_connected_account_id"),
    deprecatedComposioConnectedAccountStatus: text(
      "composio_connected_account_status",
    ),
    deprecatedComposioRedirectUrl: text("composio_redirect_url"),
    deprecatedComposioAuthSchemaMode: text("composio_auth_schema_mode", {
      enum: Object.values(DeprecatedComposioAuthMode) as [
        DeprecatedComposioAuthMode,
      ],
    }),
    deprecatedComposioAuthFields: customJsonb<Record<string, string>>(
      "composio_auth_fields",
    )
      .default({})
      .notNull(),
    // contains the client information for the MCP OAuth client, including the client_id and client_secret
    mcpOauthClientInfo: customJsonb<OAuthClientInformation>(
      "mcp_oauth_client_info",
    ),
    mcpOauthTokens: customJsonb<OAuthTokens>("mcp_oauth_tokens"),
    mcpOauthLastRefreshedAt: timestamp("mcp_oauth_last_refreshed_at", {
      withTimezone: true,
    }).defaultNow(),
  }),
  (table) => {
    return [
      index("context_tool_providers_context_key_idx").on(table.contextKey),
      index("tool_provider_user_contexts_tool_provider_id_idx").on(
        table.toolProviderId,
      ),
      unique("context_tool_providers_context_key_tool_provider_idx").on(
        table.contextKey,
        table.toolProviderId,
      ),
    ];
  },
);
export const toolProviderUserContextRelations = relations(
  toolProviderUserContexts,
  ({ one }) => ({
    toolProvider: one(toolProviders, {
      fields: [toolProviderUserContexts.toolProviderId],
      references: [toolProviders.id],
    }),
  }),
);
// These are effectively sessions for the MCP OAuth flow.
export const mcpOauthClients = pgTable(
  "mcp_oauth_clients",
  ({ text, timestamp }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('moc_')`),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    toolProviderUserContextId: text("tool_provider_user_context_id")
      .references(() => toolProviderUserContexts.id, { onDelete: "cascade" })
      .notNull(),
    sessionInfo:
      customJsonb<SessionClientInformation>("client_information").notNull(),
    // must be generated on the client before insertion
    sessionId: uuid("session_id").notNull(),
    codeVerifier: text("code_verifier"),
  }),
  (table) => [
    index("mcp_oauth_clients_tool_provider_user_context_id_idx").on(
      table.toolProviderUserContextId,
    ),
  ],
);

export type DBMcpOauthClient = typeof mcpOauthClients.$inferSelect;
export const mcpOauthClientRelations = relations(
  mcpOauthClients,
  ({ one }) => ({
    toolProviderUserContext: one(toolProviderUserContexts, {
      fields: [mcpOauthClients.toolProviderUserContextId],
      references: [toolProviderUserContexts.id],
    }),
  }),
);
export type DBToolProviderUserContext =
  typeof toolProviderUserContexts.$inferSelect;

export const tamboUsers = pgTable(
  "tambo_users",
  ({ text, timestamp, uuid, boolean, integer }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('tu_')`),
    userId: uuid("user_id")
      .notNull()
      .unique()
      .references(() => authUsers.id, { onDelete: "cascade" }),

    // Activity tracking
    lastActivityAt: timestamp("last_activity_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    /** @deprecated - Use actual project count from relations instead of cached flag */
    deprecatedHasSetupProject: boolean("has_setup_project")
      .notNull()
      .default(false),

    // Welcome email tracking
    welcomeEmailSent: boolean("welcome_email_sent").notNull().default(false),
    welcomeEmailError: text("welcome_email_error"),
    welcomeEmailSentAt: timestamp("welcome_email_sent_at", {
      withTimezone: true,
    }),

    /** @deprecated - Reactivation email feature removed, column kept for data preservation */
    deprecatedReactivationEmailSentAt: timestamp("reactivation_email_sent_at", {
      withTimezone: true,
    }),
    /** @deprecated - Reactivation email feature removed, column kept for data preservation */
    deprecatedReactivationEmailCount: integer("reactivation_email_count")
      .notNull()
      .default(0),

    // Legal acceptance tracking
    legalAccepted: boolean("legal_accepted").notNull().default(false),
    legalAcceptedAt: timestamp("legal_accepted_at", { withTimezone: true }),
    legalVersion: text("legal_version"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  }),
  (table) => ({
    userIdIdx: index("idx_tambo_users_user_id").on(table.userId),
    lastActivityIdx: index("idx_tambo_users_last_activity").on(
      table.lastActivityAt,
    ),
    /** @deprecated - Reactivation email feature removed, index kept for data preservation */
    deprecatedReactivationSentIdx: index(
      "idx_tambo_users_reactivation_sent",
    ).on(table.deprecatedReactivationEmailSentAt),
    welcomeEmailSentIdx: index("idx_tambo_users_welcome_email_sent").on(
      table.welcomeEmailSent,
    ),
    legalAcceptedIdx: index("idx_tambo_users_legal_accepted").on(
      table.legalAccepted,
    ),
    legalAcceptanceConsistent: check(
      "chk_tambo_users_legal_consistency",
      sql`(NOT ${table.legalAccepted}) OR (${table.legalAcceptedAt} IS NOT NULL AND ${table.legalVersion} IS NOT NULL)`,
    ),
  }),
);

export type DBTamboUser = typeof tamboUsers.$inferSelect;

/* The rest of the file below this comment remains unchanged except where noted */

export const projectLogs = pgTable(
  "project_logs",
  ({ text, timestamp }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('pl_')`),
    projectId: text("project_id")
      .references(() => projects.id, { onDelete: "cascade" })
      .notNull(),
    threadId: text("thread_id").references(() => threads.id), // nullable
    timestamp: timestamp("timestamp", { withTimezone: true })
      .default(sql`clock_timestamp()`)
      .notNull(),
    level: text("level", {
      enum: Object.values<string>(LogLevel) as [LogLevel],
    }).notNull(),
    message: text("message").notNull(),
    metadata: customJsonb<Record<string, unknown>>("metadata"),
  }),
  (table) => [
    index("project_logs_project_idx").on(table.projectId),
    index("project_logs_thread_idx").on(table.threadId),
    index("project_logs_timestamp_idx").on(table.timestamp),
  ],
);

export type DBProjectLog = typeof projectLogs.$inferSelect;

// MCP usage events (anonymous)
export const mcpUsage = pgTable(
  "mcp_usage",
  ({ text, timestamp }) => ({
    id: text("id")
      .primaryKey()
      .notNull()
      .unique()
      .default(sql`generate_custom_id('mu_')`),
    createdAt: timestamp("created_at", { withTimezone: true })
      .defaultNow()
      .notNull(),
    transport: text("transport"),
    toolName: text("tool_name"),
    query: text("query"),
    response: text("response"),
    metadata: customJsonb<Record<string, unknown>>("metadata"),
  }),
  (table) => [
    index("mcp_usage_created_at_idx").on(table.createdAt),
    index("mcp_usage_tool_name_idx").on(table.toolName),
  ],
);

export type DBMcpUsage = typeof mcpUsage.$inferSelect;
